name: Build and publish
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  IMAGE: carlosalgms/composer-and-node-ci

jobs:
  build_latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [php8, php7.1]
        include:
          - tag: php8
            image: carlosalgms/composer-and-node-ci
            buildArgs: ""
            tags: ${{ matrix.image }}:latest,${{ matrix.image }}:${{ matrix.tag }}

          - tag: php7.1
            image: carlosalgms/composer-and-node-ci
            buildArgs: |
              PHP_VERSION=7.1
              DEPLOYER_VERSION=v6.6.0
              COMPOSER_VERSION=2.2.18
            tags: ${{ matrix.image }}:${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          pull: true
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: ${{ matrix.image }}:${{ matrix.tag }}
          cache-to: type=inline
          build-args: ${{ matrix.buildArgs }}
          tags: ${{ matrix.tags }}
