name: Build and publish
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  IMAGE: carlosalgms/composer-and-node-ci

jobs:
  build_latest:
    runs-on: ubuntu-latest
    env:
      TAG: php8
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: ${{ env.IMAGE }}:${{ env.TAG }}
          cache-to: type=inline
          tags: ${{ env.IMAGE }}:latest,${{ env.IMAGE }}:${{ env.TAG }}


  build_71:
    runs-on: ubuntu-latest
    env:
      TAG: php7.1
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build 7.1 and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: ${{ env.IMAGE }}:${{ env.TAG }}
          cache-to: type=inline
          build-args: |
            PHP_VERSION=7.1
            DEPLOYER_VERSION=v6.6.0
            COMPOSER_VERSION=2.2.18
          tags: ${{ env.IMAGE }}:${{ env.TAG }}
