name: Build and publish
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build_latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: carlosalgms/composer-and-node-ci:latest

  build_71:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build 7.1 and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            FROM_IMAGE=php:7.1
            PECL_EXT=imagick-3.5.1
            ENABLE_EXT=imagick
            PHP_EXT=gd mysqli pdo_mysql opcache pspell mcrypt bcmath exif zip
          tags: carlosalgms/composer-and-node-ci:php7.1
