name: Build and publish
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build_latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - run: docker pull carlosalgms/composer-and-node-ci:php8

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: |
            carlosalgms/composer-and-node-ci:php8
          tags: carlosalgms/composer-and-node-ci:latest,carlosalgms/composer-and-node-ci:php8


  build_7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - run: docker pull carlosalgms/composer-and-node-ci:php7

      - name: Build 7 and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: |
            carlosalgms/composer-and-node-ci:php7
          build-args: |
            FROM_IMAGE=php:7-cli
          tags: carlosalgms/composer-and-node-ci:php7


  build_71:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        id: docker_login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - run: docker pull carlosalgms/composer-and-node-ci:php7.1

      - name: Build 7.1 and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: |
            carlosalgms/composer-and-node-ci:php7.1
          build-args: |
            FROM_IMAGE=php:7.1-cli
            DEPLOYER_VERSION="v6.6.0"
            PECL_EXT=
            ENABLE_EXT=
            PHP_EXT=mysqli pspell zip mcrypt
          tags: carlosalgms/composer-and-node-ci:php7.1
